//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EyeKeyLoggerP.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="EyeDenticaService", ConfigurationName="ServiceReference.IDataService")]
    public interface IDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="EyeDenticaService/IDataService/getPrediction", ReplyAction="EyeDenticaService/IDataService/getPredictionResponse")]
        double getPrediction();
        
        [System.ServiceModel.OperationContractAttribute(Action="EyeDenticaService/IDataService/getPrediction", ReplyAction="EyeDenticaService/IDataService/getPredictionResponse")]
        System.Threading.Tasks.Task<double> getPredictionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="EyeDenticaService/IDataService/flushUserRecord", ReplyAction="EyeDenticaService/IDataService/flushUserRecordResponse")]
        void flushUserRecord(string record);
        
        [System.ServiceModel.OperationContractAttribute(Action="EyeDenticaService/IDataService/flushUserRecord", ReplyAction="EyeDenticaService/IDataService/flushUserRecordResponse")]
        System.Threading.Tasks.Task flushUserRecordAsync(string record);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDataServiceChannel : EyeKeyLoggerP.ServiceReference.IDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DataServiceClient : System.ServiceModel.ClientBase<EyeKeyLoggerP.ServiceReference.IDataService>, EyeKeyLoggerP.ServiceReference.IDataService {
        
        public DataServiceClient() {
        }
        
        public DataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public double getPrediction() {
            return base.Channel.getPrediction();
        }
        
        public System.Threading.Tasks.Task<double> getPredictionAsync() {
            return base.Channel.getPredictionAsync();
        }
        
        public void flushUserRecord(string record) {
            base.Channel.flushUserRecord(record);
        }
        
        public System.Threading.Tasks.Task flushUserRecordAsync(string record) {
            return base.Channel.flushUserRecordAsync(record);
        }
    }
}
